spring:
  application:
    name: problem-solving-journal

  datasource:
    url: jdbc:h2:file:./data/journal
    username: sa
    password: ""

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
